export const EVENT_TICKET_RESERVATION_MINUTES = Number(
  process.env.EVENT_TICKET_RESERVATION_MINUTES ?? 15,
);

export const EVENT_TRANSACTION_MAX_RETRIES = 3;
export const EVENT_TRANSACTION_RETRY_BASE_DELAY_MS = 40;
export const EVENT_ORDER_EXPIRATION_BATCH_SIZE = 50;
export const TICKET_CODE_RETRY_LIMIT = 8;
export const QR_TOKEN_BYTES = 32;
export const ACCESS_TOKEN_BYTES = 32;
